### ISSUE TITLE
Rewrite the #568 proof against the real auth module with route mocks (the Auth stub rots with every new Auth call)

### ISSUE THREAD

**Issue by vtggit** [vtggit/AIDW#610]
## Problem

`app/tests/issue568_surgical.spec.js` (the proof of #568) replaces the whole `Auth` module by route-fulfilling `/js/auth.js` with a stub. Every new `Auth` call the product gains breaks it: after #589 and #608 the stub lacks `isAdmin` and `isAuthenticated`, and #588 (the production-only redirect) cannot be built without amending it again. Replayed 2026-09-15: the stub scenario now throws `Auth.isAdmin is not a function` at boot. Its scenario 1 (`Auth.init()` rejecting) is unreachable with the real module, which never rejects.

## Proposed acceptance criteria

- `app/tests/issue568_surgical.spec.js` is rewritten against the real `app/js/auth.js` and drives only the DOM and the network: it registers one `page.route('**/api/**')` handler that branches on the URL before navigation (mocking `/api/auth/config` as `authEnabled: true, authMode: development`, `/api/auth/me` as an authenticated user with roles, and the panel endpoints), loads `/studio.html` with the token only in the URL hash, and proves that every module's first `/api/**` request carries the Authorization header and none returns 401; a second pass with `/api/auth/config` unreachable proves the modules still start and no navigation happens; no scenario replaces `window.Auth`, `window.ApiClient` or the `/js/auth.js` script, and the rejecting-init scenario is dropped as unreachable. The rewritten spec passes in the served-app Playwright run. [scoped-write: app/tests/issue568_surgical.spec.js] [supersedes-spec: app/tests/issue568_surgical.spec.js]

### Moderator Decision (Round 2) — 2026-09-15 21:56 UTC

**Decision:** follow_ups_created
**Summary:** No blockers or accepted scope changes; incorporated the 401 route-mock requirement and tracked a production fail-closed negative test as a follow-up.
**Reasoning:** Follow-up items were identified and created this round

**New acceptance criteria:**
- [ ] The rewritten #568 proof must configure protected route mocks for /api/auth/me and panel endpoints to return 401 when Authorization is missing or invalid after identity is expected, rather than blindly succeeding.

**Linked issues:**
- Follow-up: #615

<sub>Logged by Multi-Agent Deliberation System (moderator-controlled change)</sub>

## Acceptance Criteria

- [ ] AC-1 `app/tests/issue568_surgical.spec.js` is rewritten against the real `app/js/auth.js` and drives only the DOM and the network: it registers one `page.route('**/api/**')` handler that branches on the URL before navigation (mocking `/api/auth/config` as `authEnabled: true, authMode: development`, `/api/auth/me` as an authenticated user with roles, and the panel endpoints), loads `/studio.html` with the token only in the URL hash, and proves that every module's first `/api/**` request carries the Authorization header and none returns 401; a second pass with `/api/auth/config` unreachable proves the modules still start and no navigation happens; no scenario replaces `window.Auth`, `window.ApiClient` or the `/js/auth.js` script, and the rejecting-init scenario is dropped as unreachable. The rewritten spec passes in the served-app Playwright run. [scoped-write: app/tests/issue568_surgical.spec.js] [supersedes-spec: app/tests/issue568_surgical.spec.js] [reuse: app/js/auth.js, app/js/api.js, app/js/config.js, app/studio.html, app/js/wizard.js, app/js/sequences.js, app/js/sources.js]
- [ ] AC-2 The proof must assert that the authentication token is stored in `sessionStorage['aicrm_token']` after successful migration, not in `localStorage['auth_token']`. [scoped-write: app/tests/issue568_surgical.spec.js] [reuse: app/js/auth.js, app/js/api.js, app/js/config.js, app/studio.html, app/js/wizard.js, app/js/sequences.js, app/js/sources.js]
- [ ] AC-3 The proof must seed authentication via the URL hash `#access_token=<token>` and verify that `auth.js` migrates it into `sessionStorage['aicrm_token']`. [scoped-write: app/tests/issue568_surgical.spec.js] [reuse: app/js/auth.js, app/js/api.js, app/js/config.js, app/studio.html, app/js/wizard.js, app/js/sequences.js, app/js/sources.js]
- [ ] AC-4 The proof must not assert an `Auth.init()` rejection path that the real module cannot produce; it should instead test the actual resolved value (`undefined` or user object) and any downstream redirect behavior in `studio.html`. [scoped-write: app/tests/issue568_surgical.spec.js] [reuse: app/js/auth.js, app/js/api.js, app/js/config.js, app/studio.html, app/js/wizard.js, app/js/sequences.js, app/js/sources.js]
- [ ] AC-5 The rewritten #568 proof must configure protected route mocks for /api/auth/me and panel endpoints to return 401 when Authorization is missing or invalid after identity is expected, rather than blindly succeeding. [scoped-write: app/tests/issue568_surgical.spec.js] [reuse: app/js/auth.js, app/js/api.js, app/js/config.js, app/studio.html, app/js/wizard.js, app/js/sequences.js, app/js/sources.js]

## Issue / PR Linkage
- Follow-up: #614

- Follow-up: #615

## Panel Recommendations

- **auth_expert, api_testing_expert** — _incorporated into the AC_: Assert token storage in sessionStorage['aicrm_token'] rather than localStorage['auth_token']
  - _why:_ The current spec tests a non-existent contract; the real module uses sessionStorage. This correction is required to validate the actual auth.js behavior and is expressible as a testable AC.
- **api_testing_expert** — _incorporated into the AC_: Specify the real token migration hash key #access_token=... in acceptance criteria
  - _why:_ The current spec uses an incorrect hash key that cannot authenticate against the real module. This is a required clarification to deliver the proof correctly.
- **auth_expert, security_expert** — _incorporated into the AC_: Remove or replace the unreachable Auth.init rejection scenario with a test of actual resolved behavior
  - _why:_ The real auth.js swallows failures and resolves undefined rather than rejecting; asserting a rejection path that cannot occur makes the proof invalid. This correction is required for an accurate rewrite.
- **security_expert** — _follow-up #614_: Make studio.html treat undefined user as unauthenticated and redirect to login
  - _why:_ This is a concrete, buildable security hardening that addresses fail-open behavior but is not required to complete the #568 proof rewrite; it should be tracked as separate work.
- **auth_expert, api_testing_expert, security_expert** — _declined_: Validate real Authorization header lifecycle and response-shape consumption in the proof
  - _why:_ This is already implied by the parent issue's goal of rewriting against the real auth module with route mocks; adding it as a separate AC would restate existing scope without introducing a new testable requirement beyond what the other incorporated ACs cover.
- **auth_expert, api_testing_expert** — _incorporated into the AC_: Protected route mocks for /api/auth/me and panel endpoints should return 401 when Authorization is missing or invalid after identity is expected.
  - _why:_ This clarifies the parent issue's requirement to use real auth behavior with route mocks; without it, the proof could pass while mocking an unsafe backend contract. It is a testable assertion the current Playwright setup can satisfy.
- **auth_expert** — _declined_: Pin the real identity lifecycle at the boundary where Auth.init() consumes the migrated token, not only downstream panels.
  - _why:_ This is a useful design clarification, but it largely restates the parent issue's goal of proving behavior against the real auth module. It does not identify a missing prerequisite or an impossible requirement, so no separate tracked action is needed this round.
- **api_testing_expert** — _declined_: Do not require #auth-status to show unauthenticated/error in the config-unreachable pass because real Auth.init() catches /api/auth/me failures.
  - _why:_ This is a correction to another agent's proposed UI assertion rather than new work required by the parent issue. If an existing acceptance criterion requires that specific status text, it should be revisited during AC review, but no blocker or scope change is established from this round alone.
- **security_expert** — _follow-up #615_: Pair the dev-mode modules-start assertion with a production fail-closed negative pass proving unauthenticated boot cannot obtain protected data.
  - _why:_ Concrete and valuable, but it extends beyond the immediate #568 proof rewrite. The parent issue can proceed by rewriting the proof against the real auth module with route mocks; this hardening pass is better tracked separately.

## Governance & Blockers
✅ **May proceed** — no blocking governance concerns.

**Resolution:** `completed_with_scope_change` · **may_proceed:** True

## Panel Open Questions

- ~~OQ-1 Should `Auth.init()` be fixed to explicitly return `_user` or throw on 401 so `studio.html`’s redirect logic becomes reachable? If not, the spec must encode the current fail-open behavior as accept... (resolved)~~
  - **A:** No — this issue does not modify `Auth.init()` or `studio.html`; it is a spec-only rewrite that encodes the current fail-open behavior (init resolves `undefined` on 401, modules still start) as the accepted baseline for the proof. The fix to make redirect logic reachable (treat undefined user as unauthenticated and redirect) is already tracked as follow-up #614 per the Round-2 panel decision, so it is deliberately deferred out of this issue's scope. AC-4 already constrains the spec to assert only what the real module can produce (`undefined` or a user object), which is exactly "encode current b …
- ~~OQ-2 Is “config unreachable + unauthenticated” intentionally allowed to start modules in dev mode? If yes, which protected endpoints are guaranteed 401 by backend and should the UI block module init unt... (resolved)~~
  - **A:** Yes — in dev mode with `/api/auth/config` unreachable, modules starting without an authenticated identity is the intentional current behavior that AC-1's second pass exists to prove ("modules still start and no navigation happens"). The UI does not block module init; each panel handles its own 401 responses via existing error paths. Regarding which endpoints are guaranteed 401: every backend route behind `require_authenticated_user` or `require_role(ROLE_ADMIN)` (e.g., `backend/app/api/discovery.py:18`, `backend/app/api/profiling.py:18`, `backend/app/api/connection_tests.py:39`) returns 401 wi …
- ~~OQ-3 Confirm prod unauthenticated boot may start UI as long as API denies data, or should this issue also require code changing `Auth.init`/`studio.html` to block module init? For spec-only scope, I rec... (resolved)~~
  - **A:** Confirmed — for this spec-only issue, production unauthenticated boot may start the UI shell as long as every protected API call is denied with 401; no code change to `Auth.init` or `studio.html` to block module init is required here. The stronger guarantee (a dedicated negative pass proving an unauthenticated prod boot cannot obtain any protected data end-to-end) is already tracked as follow-up #615 per the Round-2 decision, so it is recorded for that epic and does not alter this issue's acceptance criteria. IMPACT: informational

## CodeAgent Contract

<details>
<summary>codeagent-contract v1 (auto-generated — machine-managed)</summary>

```json
{
  "acceptance_criteria": [
    {
      "checked": false,
      "id": "AC-1",
      "retired_round": null,
      "status": "active",
      "text": "`app/tests/issue568_surgical.spec.js` is rewritten against the real `app/js/auth.js` and drives only the DOM and the network: it registers one `page.route('**/api/**')` handler that branches on the URL before navigation (mocking `/api/auth/config` as `authEnabled: true, authMode: development`, `/api/auth/me` as an authenticated user with roles, and the panel endpoints), loads `/studio.html` with the token only in the URL hash, and proves that every module's first `/api/**` request carries the Authorization header and none returns 401; a second pass with `/api/auth/config` unreachable proves the modules still start and no navigation happens; no scenario replaces `window.Auth`, `window.ApiClient` or the `/js/auth.js` script, and the rejecting-init scenario is dropped as unreachable. The rewritten spec passes in the served-app Playwright run. [scoped-write: app/tests/issue568_surgical.spec.js] [supersedes-spec: app/tests/issue568_surgical.spec.js] [reuse: app/js/auth.js, app/js/api.js, app/js/config.js, app/studio.html, app/js/wizard.js, app/js/sequences.js, app/js/sources.js]"
    },
    {
      "checked": false,
      "id": "AC-2",
      "retired_round": null,
      "status": "active",
      "text": "The proof must assert that the authentication token is stored in `sessionStorage['aicrm_token']` after successful migration, not in `localStorage['auth_token']`. [scoped-write: app/tests/issue568_surgical.spec.js] [reuse: app/js/auth.js, app/js/api.js, app/js/config.js, app/studio.html, app/js/wizard.js, app/js/sequences.js, app/js/sources.js]"
    },
    {
      "checked": false,
      "id": "AC-3",
      "retired_round": null,
      "status": "active",
      "text": "The proof must seed authentication via the URL hash `#access_token=<token>` and verify that `auth.js` migrates it into `sessionStorage['aicrm_token']`. [scoped-write: app/tests/issue568_surgical.spec.js] [reuse: app/js/auth.js, app/js/api.js, app/js/config.js, app/studio.html, app/js/wizard.js, app/js/sequences.js, app/js/sources.js]"
    },
    {
      "checked": false,
      "id": "AC-4",
      "retired_round": null,
      "status": "active",
      "text": "The proof must not assert an `Auth.init()` rejection path that the real module cannot produce; it should instead test the actual resolved value (`undefined` or user object) and any downstream redirect behavior in `studio.html`. [scoped-write: app/tests/issue568_surgical.spec.js] [reuse: app/js/auth.js, app/js/api.js, app/js/config.js, app/studio.html, app/js/wizard.js, app/js/sequences.js, app/js/sources.js]"
    },
    {
      "checked": false,
      "id": "AC-5",
      "retired_round": null,
      "status": "active",
      "text": "The rewritten #568 proof must configure protected route mocks for /api/auth/me and panel endpoints to return 401 when Authorization is missing or invalid after identity is expected, rather than blindly succeeding. [scoped-write: app/tests/issue568_surgical.spec.js] [reuse: app/js/auth.js, app/js/api.js, app/js/config.js, app/studio.html, app/js/wizard.js, app/js/sequences.js, app/js/sources.js]"
    }
  ],
  "decision": {
    "decision": "follow_ups_created",
    "id": "D-2",
    "reasoning": "Follow-up items were identified and created this round",
    "round": 2,
    "summary": "No blockers or accepted scope changes; incorporated the 401 route-mock requirement and tracked a production fail-closed negative test as a follow-up."
  },
  "governance": {
    "blockers": [],
    "may_proceed": true,
    "resolution_state": "completed_with_scope_change"
  },
  "issue": 610,
  "next_id": {
    "ac": 6,
    "aq": 1,
    "oq": 4
  },
  "open_questions_author": [],
  "open_questions_panel": [
    {
      "id": "OQ-1",
      "resolved_round": null,
      "status": "resolved",
      "text": "Should `Auth.init()` be fixed to explicitly return `_user` or throw on 401 so `studio.html`\u2019s redirect logic becomes reachable? If not, the spec must encode the current fail-open behavior as accept..."
    },
    {
      "id": "OQ-2",
      "resolved_round": null,
      "status": "resolved",
      "text": "Is \u201cconfig unreachable + unauthenticated\u201d intentionally allowed to start modules in dev mode? If yes, which protected endpoints are guaranteed 401 by backend and should the UI block module init unt..."
    },
    {
      "id": "OQ-3",
      "resolved_round": null,
      "status": "resolved",
      "text": "Confirm prod unauthenticated boot may start UI as long as API denies data, or should this issue also require code changing `Auth.init`/`studio.html` to block module init? For spec-only scope, I rec..."
    }
  ],
  "schema": "codeagent-contract",
  "updated_round": 2,
  "version": 1
}
```
</details>

**Comment by vtggit** [comment]
Contract amendment (operator delegation): the staged emission returned no file twice, and thanks to CodeAgent#762 the build log now shows why -- the model replied "I need to examine the actual app/js/auth.js and related frontend files before rewriting this spec". A spec that drives the real module needs that module in front of the builder: the criterion now carries [reuse: …] for auth.js, api.js, config.js, studio.html and the three panel modules the boot starts. Rebuild queued.
